package registry

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
	"unicode"
)

// Generate writes the Go constants for a registry: one for every attribute, span, event and metric
// name, and one for every value of an enumerated attribute. Code uses these and never a string
// literal, so a name that is not in the registry does not compile.
func Generate(r *Registry, pkg, prefix string) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Code generated by internal/registry/gen from telemetry/registry. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)

	b.WriteString("// Attribute names: ynr's own, then the OpenTelemetry attributes it uses.\nconst (\n")
	for _, a := range r.Attributes {
		fmt.Fprintf(&b, "\t// %s\n\tAttr%s = %q\n", oneLine(a.Brief), goName(prefix, a.ID), a.ID)
	}
	for _, id := range r.Standard {
		fmt.Fprintf(&b, "\tAttr%s = %q\n", goName(prefix, id), id)
	}
	b.WriteString(")\n\n")

	if len(r.Spans) > 0 {
		b.WriteString("// Span names.\nconst (\n")
		for _, s := range r.Spans {
			fmt.Fprintf(&b, "\t// %s\n\tSpan%s = %q\n", oneLine(s.Brief), goName(prefix, s.Name), s.Name)
		}
		b.WriteString(")\n\n")
	}

	if len(r.Events) > 0 {
		b.WriteString("// Event names.\nconst (\n")
		for _, e := range r.Events {
			fmt.Fprintf(&b, "\t// %s\n\tEvent%s = %q\n", oneLine(e.Brief), goName(prefix, e.Name), e.Name)
		}
		b.WriteString(")\n\n")
	}

	if len(r.Metrics) > 0 {
		b.WriteString("// Metric names.\nconst (\n")
		for _, m := range r.Metrics {
			fmt.Fprintf(&b, "\t// %s\n\tMetric%s = %q\n", oneLine(m.Brief), goName(prefix, m.Name), m.Name)
		}
		b.WriteString(")\n\n")
	}

	for _, a := range r.Attributes {
		if len(a.Members) == 0 {
			continue
		}
		fmt.Fprintf(&b, "// Values of %s.\nconst (\n", a.ID)
		for _, m := range a.Members {
			fmt.Fprintf(&b, "\t// %s\n\t%s%s = %q\n", oneLine(m.Brief), goName(prefix, a.ID), goName(prefix, m.ID), m.Value)
		}
		b.WriteString(")\n\n")
	}

	return format.Source(b.Bytes())
}

// goName turns a registry name into an exported Go identifier: ynr.collector.id is CollectorID,
// cloudevents.event_id is CloudeventsEventID. The tool's prefix, such as ynr., is dropped.
func goName(prefix, id string) string {
	id = strings.TrimPrefix(id, prefix)
	var b strings.Builder
	for _, w := range strings.FieldsFunc(id, func(r rune) bool { return r == '.' || r == '_' || r == '-' }) {
		switch w {
		case "id":
			b.WriteString("ID")
		case "url":
			b.WriteString("URL")
		default:
			rs := []rune(w)
			rs[0] = unicode.ToUpper(rs[0])
			b.WriteString(string(rs))
		}
	}
	return b.String()
}

func oneLine(s string) string { return strings.Join(strings.Fields(s), " ") }
