// Code generated by internal/registry/gen from telemetry/registry. DO NOT EDIT.

package names

// Attribute names: ynr's own, then the OpenTelemetry attributes it uses.
const (
	// How far the record can be trusted, decided by the spool folder it was written in and never by the record (ADR-003).
	AttrProvenance = "ynr.provenance"
	// Why a run's records carry no factory attributes.
	AttrProvenanceWarning = "ynr.provenance.warning"
	// The collector that stamped the record: a runner pool or a host (ADR-003).
	AttrCollectorID = "ynr.collector.id"
	// The job within the collector's pool, recorded as data and never as identity.
	AttrCollectorInstance = "ynr.collector.instance"
	// Set only when ynr has no learned registry for the record's service.name and service.version (ADR-007); the record is kept.
	AttrRegistry = "ynr.registry"
	// A name a record used that its tool's registry does not declare. Only on ynr.registry.unknown_names, and capped.
	AttrRegistryName   = "ynr.registry.name"
	AttrServiceName    = "service.name"
	AttrServiceVersion = "service.version"
)

// Metric names.
const (
	// Closed spool files deleted unshipped because the spool reached its cap (ADR-004).
	MetricSpoolEvicted = "ynr.spool.evicted"
	// Names records used that their tool's learned registry does not declare, by service, version and name. Counted, never rejected; the distinct names are capped (ADR-007).
	MetricRegistryUnknownNames = "ynr.registry.unknown_names"
)

// Values of ynr.provenance.
const (
	// Written by ynf, outside any run.
	ProvenanceFactory = "factory"
	// Written by a long-lived hosted server.
	ProvenanceService = "service"
	// Written inside one run.
	ProvenanceRun = "run"
	// Written on a laptop outside a factory.
	ProvenanceLocal = "local"
)

// Values of ynr.provenance.warning.
const (
	// A run's records with no manifest from ynf.
	ProvenanceWarningNoManifest = "no-manifest"
	// A run's records whose manifest was refused.
	ProvenanceWarningBadManifest = "bad-manifest"
)

// Values of ynr.registry.
const (
	// ynr learned no registry for the record's service and version.
	RegistryUnknown = "unknown"
)
